// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1jzymt0vhtBdGz4YoTXY73-YXM2ESGDc',
    appId: '1:207440156704:web:e86e919e9a469b18174445',
    messagingSenderId: '207440156704',
    projectId: 'secretgarden-app',
    authDomain: 'secretgarden-app.firebaseapp.com',
    databaseURL: 'https://secretgarden-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'secretgarden-app.firebasestorage.app',
    measurementId: 'G-NRT4Q6YTXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_mpozTz7iC_w02svX-E5Ej7DyAZ2Bsq4',
    appId: '1:207440156704:android:bfbd7f26bd24f3d8174445',
    messagingSenderId: '207440156704',
    projectId: 'secretgarden-app',
    databaseURL: 'https://secretgarden-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'secretgarden-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI-N3NMEbJEV_0wBEzij11KoBOXOKuS6w',
    appId: '1:207440156704:ios:07088e516e428af5174445',
    messagingSenderId: '207440156704',
    projectId: 'secretgarden-app',
    databaseURL: 'https://secretgarden-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'secretgarden-app.firebasestorage.app',
    iosBundleId: 'com.example.secretgardenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI-N3NMEbJEV_0wBEzij11KoBOXOKuS6w',
    appId: '1:207440156704:ios:07088e516e428af5174445',
    messagingSenderId: '207440156704',
    projectId: 'secretgarden-app',
    databaseURL: 'https://secretgarden-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'secretgarden-app.firebasestorage.app',
    iosBundleId: 'com.example.secretgardenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1jzymt0vhtBdGz4YoTXY73-YXM2ESGDc',
    appId: '1:207440156704:web:256fff22df54a41b174445',
    messagingSenderId: '207440156704',
    projectId: 'secretgarden-app',
    authDomain: 'secretgarden-app.firebaseapp.com',
    databaseURL: 'https://secretgarden-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'secretgarden-app.firebasestorage.app',
    measurementId: 'G-FG513L5P1M',
  );

}